hibernate.connection.driver_class=com.mysql.cj.jdbc.Driver
hibernate.connection.url=jdbc:myql://localhost:3306/advjava
hibernate.connection.username=root
hibernate.connection.password=Nishadanjum@625
hibernate.dialect=org.hibernate.dialect.MySQLDialect
hibernate.show_sql=true
hibernate.hbm2ddl.auto=update
