spring.application.name=smart-complaint-tracker-api

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/advjava
spring.datasource.username=root
spring.datasource.password=Nishadanjum@625

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
# Swagger UI at /swagger-ui/index.html
