// <auto-generated />
using CodeFirstFluentApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeFirstFluentApi.Migrations
{
    [DbContext(typeof(EmpDbContext))]
    [Migration("20250706074803_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CodeFirstFluentApi.Models.Department", b =>
                {
                    b.Property<int>("DeptNo")
                        .HasColumnType("int");

                    b.Property<string>("DeptName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("DeptNo")
                        .HasName("PK__Departme__0148CAAE9B057EBB");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("CodeFirstFluentApi.Models.Employee", b =>
                {
                    b.Property<int>("EmpNo")
                        .HasColumnType("int")
                        .HasColumnName("empNo");

                    b.Property<decimal>("Basic")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("DeptNo")
                        .HasColumnType("int");

                    b.Property<string>("EmpName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("empName")
                        .IsFixedLength();

                    b.HasKey("EmpNo")
                        .HasName("PK__Employee__AFB335924F94DD7B");

                    b.HasIndex("DeptNo");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("CodeFirstFluentApi.Models.Employee", b =>
                {
                    b.HasOne("CodeFirstFluentApi.Models.Department", "DeptNoNavigation")
                        .WithMany("Employees")
                        .HasForeignKey("DeptNo")
                        .IsRequired()
                        .HasConstraintName("FK_Employees_Departments");

                    b.Navigation("DeptNoNavigation");
                });

            modelBuilder.Entity("CodeFirstFluentApi.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
