FROM openjdk:17-slim

WORKDIR /app

COPY mysql-connector-j-9.3.0.jar .

COPY MysqlTester.java .

RUN javac -cp mysql-connector-j-9.3.0.jar MysqlTester.java

CMD [ "java","-cp",".:mysql-connector-j-9.3.0.jar","MysqlTester" ]